### ISSUE TITLE
Train from raw pixels data

### ISSUE THREAD

**Issue by Jidenna** [sheelabhadra/Learning2Drive#4]
How do I train without VAE? 

Everytime I don't use VAE I get the error below ```
```
CarlaClient connected
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    env = DummyVecEnv([make_env(client, args.seed, vae=vae)])
  File "/home/joshua/anaconda/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 17, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/joshua/anaconda/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 17, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/joshua/Documents/Accelerating Training of DRL/utils/utils.py", line 116, in _init
    n_stack=n_stack)
  File "/home/joshua/Documents/Accelerating Training of DRL/environment/env.py", line 38, in __init__
    shape=(1, self.z_size + self.n_commands * n_command_history),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
```
Using this  python train.py --algo sac -n 10000

**Comment by sheelabhadra** [comment]
The code has been set up to only accept 1-D arrays as input (line 38 in env.py). If you want to use raw pixels as input, you will need to change the observation space in env.py and the policy (see utils.py and the hyperparameters directory) to train your agent.
